### ISSUE TITLE
SQL batch api script fails

### ISSUE THREAD

**Issue by jsanz** [CartoDB/carto-python#43]
Looks like the last change to 1.0.0. was not merged

```shell
[env] $ python sql_batch_api_jobs.py create --query 'select version()'
Traceback (most recent call last):
  File "sql_batch_api_jobs.py", line 55, in <module>
    createJob = batchSQLClient.create(args.query)
  File "/home/jsanz/src/sdks/carto-python/examples/env/src/carto/carto/sql.py", line 87, in create
    data = self.send(self.api_url, http_method="POST", json_body={"query": sql_query}, http_header=header)
  File "/home/jsanz/src/sdks/carto-python/examples/env/src/carto/carto/sql.py", line 76, in send
    data = self.client.send(url, http_method=http_method, http_headers=http_header, json=json_body)
  File "/home/jsanz/src/sdks/carto-python/examples/env/src/carto/carto/auth.py", line 42, in send
    return super(APIKeyAuthClient, self).send(relative_path, http_method, **requests_args)
  File "/home/jsanz/src/sdks/carto-python/examples/env/local/lib/python2.7/site-packages/pyrestcli/auth.py", line 34, in send
    return self.session.request(http_method, url, proxies=self.proxies, **requests_args)
TypeError: request() got an unexpected keyword argument 'http_headers'
[env] $ git pull
Already up-to-date.
```

**Comment by oriolbx** [comment]
It does work to me:
 
```shell
(env) ip-10-0-32-36:carto-python oboix$ python examples/sql_batch_api_jobs.py "create" --query "select version()"
 05:18:12 PM - INFO - status: pending
 05:18:12 PM - INFO - job_id: 2d1e2a21-02fc-4834-a07f-20cde80eae73
 05:18:12 PM - INFO - created_at: 2017-02-15T16:18:12.523Z
 05:18:12 PM - INFO - updated_at: 2017-02-15T16:18:12.523Z
 05:18:12 PM - INFO - user: carto-workshops
 05:18:12 PM - INFO - query: select version()
```

🤔

**Comment by alrocar** [comment]
It is working with the 1.0.0 branch.

I hope everything to be merged in master in the following days :)
